### PR TITLE
Fix adding plates on player respawn

### LINKED ISSUE #41: Players don't respawn with plates
**Mods:**
- **CBA:** `3.15.5`
- **APS:** `0.4.2`
- **ACE:** [`0.13.6`](
[Arma3_x64_2021-07-13_19-35-54.zip](https://github.com/diwako/armor_plates_system/files/6812700/Arma3_x64_2021-07-13_19-35-54.zip)
)

**Description:**
With "Players spawn with full plates" checked, players will have plates on initial spawn; however, on respawn players do not have plates. 

**Steps to reproduce:**
- Spawn a single unit, a respawn module, and enable respawns.
- Ensure "Players spawn with full plates" is checked
- Run mission in multiplayer setting

**Expected behavior:**
Expected players to respawn with full plates on themselves.

**Where did the issue occur?**
Dedicated & Self-Hosted Multiplayer

**Additional context:**
Tested with and without ACE Medical, this had no change on the problem.
CBA was recently updated, unsure if this would have been a cause.

**Log Files:**
[Arma3_x64_2021-07-13_19-35-54.zip](https://github.com/diwako/armor_plates_system/files/6812715/Arma3_x64_2021-07-13_19-35-54.zip)

### PR DESCRIPTION
**Pull request by diwako**
closes #41

### CODE REVIEW

**Comment by fariparedes** [comment]
Thoughts on putting this plate refill code in its own function/CBA event so the code isn't duplicated?

**Comment by diwako** [comment]
own function, cba event makes not much sense

**Comment by fariparedes** [comment]
Seems like it would future proof it, given that you may one day want to add, say, a Zeus module for refilling plates.

**Comment by diwako** [comment]
That will be added once it is needed imo.

**Pull request merged**
