### PR TITLE
Updated Chinese translation

### PR DESCRIPTION
**Pull request by mihuan-0**

### CODE REVIEW

**Comment by mihuan-0** [comment]
Wait for more content to be released before merging, I will recheck the files to see if new Chinese translations need to be added ：）

**Comment by diwako** [comment]
Alright, then I shall work double time to get those other 2 merged.

**Comment by diwako** [comment]
Alright, the other pull requests are now merged. I also fixed the merge conflicts for you. So just pull and you have the latest changes.

**Comment by mihuan-0** [comment]
Thanks, the latest Chinese translation has been added.

**Pull request merged**
