### PR TITLE
Polish language for stringtable.xml

### PR DESCRIPTION
**Pull request by genjonakasone**
Added Polish translation. 100% sure no bugs in it.

### CODE REVIEW

**Comment by diwako** [comment]
Thank you for this pr :D

**Comment by diwako** [comment]
Question is this done? I would like to merge this next to avoid merge conflicts on your branch.

**Comment by genjonakasone** [comment]
> Question is this done? I would like to merge this next to avoid merge conflicts on your branch.



> Question is this done? I would like to merge this next to avoid merge conflicts on your branch.

Yes it is, I'll try to keep it up to date with new enhancements you implement.

**Comment by diwako** [comment]
Alright, would you want me to merge this or should I merge all the other feature branches first. there will be merge conflicts which i can fix for you as well.
or
Want to make another PR once everything is merged?

**Comment by genjonakasone** [comment]
> Alright, would you want me to merge this or should I merge all the other feature branches first. there will be merge conflicts which i can fix for you as well.
> or
> Want to make another PR once everything is merged?

I will make another one and add mising strings ASAP, should be able to do this today. :)

**Pull request merged**
