### PR TITLE
`switchMove` readies weapon afterwards by default

### PR DESCRIPTION
**Pull request by amsteadrayle**
Players will now have their weapon ready when they come out of reviving or pressing a wound.

### CODE REVIEW

**Comment by diwako** [comment]
1. check all instances of the event being used. it is also used in the revive animation part
2. make it a setting as I believe some people do not want to instantly have their guns out

**Comment by amsteadrayle** [comment]
I'll add the options for this, and then it should be ready to go. I'm thinking the options will be Weapon ready after reviving/pressing: Never, After canceling, or Always. 
I'm singling out canceling because of situations where you have to quickly stop reviving someone and shoot an enemy that just showed up.

For your point 1, were you referring to the `switchMove`s when someone comes out of unconscious? From my testing, running that action has no effect while someone is prone. I can pass `false` through those calls just in case.
https://github.com/diwako/armor_plates_system/blob/d292b02492c41b0ce103bd9362ba37c1baeba840/addons/main/functions/fnc_setUnconscious.sqf#L62

**Comment by diwako** [comment]
>For your point 1, were you referring to the switchMoves when someone comes out of unconscious? From my testing, running that action has no effect while someone is prone. I can pass false through those calls just in case.

The event is used for all kinds of animations. I am just warning that it is used on people being uncon, people doing the revive animation and so. It was to highlight to double check that this does not interfere in all those cases.

**Comment by amsteadrayle** [comment]
Just to be totally sure, this is everywhere `switchMove` is currently being used. The reviver cases are where the change is meant for. The revived cases are either going prone or crouching with a launcher, which should be unaffected by the `WeaponInHand` action.
But I'll go ahead and pass false in those to avoid any side effects from spooky arma jank.

image

**Comment by diwako** [comment]
Yeah that is the best solution. While this mod is tailored mostly for MJB arma, it still try to keep things open for other people which want a little different experience.

**Pull request merged**
